name: deploy
on:
  push:
    branches:
      - main
      - master

jobs:
  run-unit-tests:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.8.2

      - name: Unit Tests
        run: mvn clean package

      - name: Rename the artifact
        run: cp target/demo-0.0.1-SNAPSHOT.jar demo-${{ github.sha }}.jar

      - name: Save the artifact
        uses: actions/upload-artifact@master
        with:
          name: demo
          path: demo-${{ github.sha }}.jar

  fake-deploy:
    runs-on: self-hosted
    needs: run-unit-tests
    steps:
      - name: Get the artifact
        uses: actions/download-artifact@master
        with:
          name: demo

      - name: Fake deploy
        run: ls demo-*.jar

